# Generated by Django 4.1.3 on 2022-11-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(help_text='Click the dropdown and select your category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.status'),
        ),
    ]
