# Generated by Django 4.1.3 on 2022-11-17 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(help_text='Click the dropdown and select your category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_category', to='todo.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(help_text='Click the dropdown and select your category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status', to='todo.status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
